IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Todos' AND COLUMN_NAME = 'IsDeleted')
BEGIN
    ALTER TABLE Todos ADD IsDeleted BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Clients' AND COLUMN_NAME = 'IsDeleted')
BEGIN
    ALTER TABLE Clients ADD IsDeleted BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Invoices' AND COLUMN_NAME = 'IsDeleted')
BEGIN
    ALTER TABLE Invoices ADD IsDeleted BIT NOT NULL DEFAULT 0;
END
